# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Dell/OneDrive/Desktop/m_p_AES/m_p_project_1/.Xil/Vivado-22752-DESKTOP-H0U5LE6/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xa7a12tcsg325-1Q

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Dell/OneDrive/Desktop/m_p_AES/m_p_project_1/m_p_project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Dell/OneDrive/Desktop/m_p_AES/m_p_project_1/m_p_project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Dell/OneDrive/Desktop/m_p_AES/m_p_project_1/m_p_project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/Sboxd.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/aescipher.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/decrypt.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/decryptlastround.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/encryptSbox.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/first9rounds.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/keygeneration.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/lastround.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/m_lookuptabel14.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/m_lookuptable11.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/m_lookuptable13.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/m_lookuptable9.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/mixcolumn.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/mixcolumndecrypt.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/sbox.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/sboxinverse.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/shiftrow.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/shiftrowd.v}
  {C:/Users/Dell/OneDrive/Desktop/m_p_AES/v files/aestopmodule.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top aestopmodule -part xa7a12tcsg325-1Q


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef aestopmodule.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file aestopmodule_utilization_synth.rpt -pb aestopmodule_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
